export const state = {
  yingbangRowData: [],
  lunfeiRowData: [],
  bngRowData: [],
  chgRowData: [],
  currentRow: null,
  currentQuery: "",
  generatedSNList: [],
  isLoading: false
};

export function createUiRefs() {
  return {
    sourceHint: document.getElementById("source-hint"),
    yingbangTab: document.getElementById("tab-yingbang"),
    lunfeiTab: document.getElementById("tab-lunfei"),
    bngTab: document.getElementById("tab-bng"),
    chgTab: document.getElementById("tab-chg"),
    yingbangWorkspace: document.getElementById("yingbang-workspace"),
    lunfeiWorkspace: document.getElementById("lunfei-workspace"),
    bngWorkspace: document.getElementById("bng-workspace"),
    chgWorkspace: document.getElementById("chg-workspace"),
    status: document.getElementById("status"),
    lunfeiStatus: document.getElementById("status-lunfei"),
    bngStatus: document.getElementById("status-bng"),
    chgStatus: document.getElementById("status-chg"),
    previewPanel: document.getElementById("preview-panel"),
    lunfeiPreviewPanel: document.getElementById("preview-panel-lunfei"),
    bngPreviewPanel: document.getElementById("preview-panel-bng"),
    chgPreviewPanel: document.getElementById("preview-panel-chg"),
    historyPanel: document.getElementById("history-panel"),
    lunfeiHistoryPanel: document.getElementById("history-panel-lunfei"),
    bngHistoryPanel: document.getElementById("history-panel-bng"),
    chgHistoryPanel: document.getElementById("history-panel-chg"),
    searchInput: document.getElementById("search-input"),
    lunfeiSearchInput: document.getElementById("search-input-lunfei"),
    bngSearchInput: document.getElementById("search-input-bng"),
    chgSearchInput: document.getElementById("search-input-chg"),
    loadBtn: document.getElementById("btn-load"),
    lunfeiLoadBtn: document.getElementById("btn-load-lunfei"),
    bngLoadBtn: document.getElementById("btn-load-bng"),
    chgLoadBtn: document.getElementById("btn-load-chg"),
    historyBtn: document.getElementById("btn-history"),
    lunfeiHistoryBtn: document.getElementById("btn-history-lunfei"),
    bngHistoryBtn: document.getElementById("btn-history-bng"),
    chgHistoryBtn: document.getElementById("btn-history-chg"),
    queryBtn: document.getElementById("btn-query"),
    lunfeiQueryBtn: document.getElementById("btn-query-lunfei"),
    bngQueryBtn: document.getElementById("btn-query-bng"),
    chgQueryBtn: document.getElementById("btn-query-chg"),
    exportBtn: document.getElementById("btn-export"),
    lunfeiExportBtn: document.getElementById("btn-export-lunfei"),
    bngExportBtn: document.getElementById("btn-export-bng"),
    chgExportBtn: document.getElementById("btn-export-chg"),
    loadingIndicator: document.getElementById("loading-indicator"),
    lunfeiLoadingIndicator: document.getElementById("loading-indicator-lunfei"),
    bngLoadingIndicator: document.getElementById("loading-indicator-bng"),
    chgLoadingIndicator: document.getElementById("loading-indicator-chg"),
    fileInput: document.getElementById("file-input"),
    lunfeiFileInput: document.getElementById("file-input-lunfei"),
    bngFileInput: document.getElementById("file-input-bng"),
    chgFileInput: document.getElementById("file-input-chg")
  };
}
